# Generated by Django 2.2.5 on 2020-10-24 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('comuna', models.CharField(max_length=100, verbose_name='Comuna')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('dormitorios', models.PositiveIntegerField(default=0)),
                ('baños', models.PositiveIntegerField(default=0)),
                ('estacionamiento', models.PositiveIntegerField(default=0)),
                ('bodega', models.PositiveIntegerField(default=0)),
                ('pisos', models.PositiveIntegerField(default=0)),
                ('huespedes', models.PositiveIntegerField(default=0)),
                ('gasto_comun', models.DecimalField(decimal_places=3, max_digits=5)),
                ('tipo', models.BooleanField()),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['direccion'],
            },
        ),
    ]
