# Generated by Django 2.2.5 on 2020-10-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0003_auto_20201024_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='gasto_comun',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
