# Generated by Django 2.2.5 on 2020-10-24 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('propiedad', '0004_auto_20201024_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrendatario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=13, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arrendatario',
                'verbose_name_plural': 'Arrendatarios',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='gasto_comun',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
        ),
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_termino', models.DateTimeField(blank=True, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('monto_reserva', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('comentario', models.TextField()),
                ('garantia', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('evaluacion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('descuento', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('saldo_pendiente', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('multa', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('comision', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('trato', models.CharField(max_length=100, verbose_name='Dirección')),
                ('dia_pago', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creación')),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.Arrendatario')),
                ('propiedad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='propiedad.Propiedad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arriendo',
                'verbose_name_plural': 'Arriendos',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
