# Generated by Django 2.2.5 on 2020-10-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0005_auto_20201024_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='evaluacion',
            field=models.CharField(max_length=100, verbose_name='Evaluación'),
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='trato',
            field=models.CharField(max_length=100, verbose_name='Trato'),
        ),
    ]
